### ISSUE TITLE
Can't install rmd-ref-app using quickstart-rmd-ref-app.sh

### ISSUE THREAD

**Issue by Aledan862** [PredixDev/predix-rmd-ref-app#31] opened 2018-09-04 19:17 UTC
I create new space, login to it.
Then type bash <(curl https://raw.githubusercontent.com/PredixDev/predix-rmd-ref-app/master/scripts/quickstart-rmd-ref-app.sh )
but on step "Registering Client on UAA to access the Predix Services" 
i see error
parse error: Expected value before ',' at line 1, column 1
**************** Error Occurred ***************************
Failure to run quickstart script
View logs at /predix/dev-space/rmd-ref-app/predix-scripts/log/quickstartlog.log

**************** Stack Trace ****************************
551 getUaaUrlFromInstance /predix/dev-space/rmd-ref-app/predix-scripts/bash/scripts/curl_helper_funcs.sh
358 __setupServices /predix/dev-space/rmd-ref-app/predix-scripts/bash/scripts/predix_services_setup.sh
190 source predix-scripts/bash/quickstart.sh
121 main /dev/fd/63

In log file only this
2018-09-04 18:55:17:  --- ERROR: There was an error getting the UAA URL...
2018-09-04 18:55:17:  --- Running the clean up script... There was an error getting the UAA URL...

In predix console, I can see only Uaa Service instance and Admin client credentials

**Comment by turnerth** [comment] 2018-09-04 19:26
Hi.  Line 551 is this.
  if [[ $responseCurl == 200* ]]; then

Three lines up is this
  responseCurl=`curl --write-out %{http_code} --output /dev/null -X POST "https://$6/services/fdhrouter/fielddatahandler/putfielddatafile" -H "Authorization: $clientToken"  -H "Content-Type: multipart/form-data;" -H "Accept: application/json" -F "file=@asset_upload_file.json" -F "putfielddata=$metadataRequest"`

$6 (wish the developer had assigned to a variable) is AssetPostBody.  

So, if you edited the  file that has the Asset Model, run it through a JSON parser.  If you didn't report back.

I just ran it and I got past that step.

**Comment by turnerth** [comment] 2018-09-04 19:43
The comment was mostly correct, but the validate string was incorrect, we fixed both.  Those are just text issues and not your problem.

The fact that is has a comma instead of a real name is the issue.  

We've seen issues when there is a period in the Unique Instance Prepender string.  e.g. instead of thomas.edison use thomasedison.    I thought there was a fix for that in the script though.  

In any case please do the 

px a

and let us know your prepender.

**Comment by Aledan862** [comment] 2018-09-05 12:18
But I have no apps, as I wrote before script created an only the UAA service instance.

[predix@predix-devbox dev-space]$ px a
Getting apps in org vakhrushev@technolink.spb.ru / space dev as vakhrushev@technolink.spb.ru...
OK

No apps found
[predix@predix-devbox dev-space]$ px s
Getting services in org vakhrushev@technolink.spb.ru / space dev as vakhrushev@technolink.spb.ru...
OK

name             service      plan   bound apps   last operation
vakhrushev-uaa   predix-uaa   Free                create succeeded

**Comment by turnerth** [comment] 2018-09-05 22:54
We found root cause.  It was some extra string values being returned from the CLI.  We changed the script to parse that out and get to the pure JSON.  It's going through testing now.  Should be out by tomorrow.

**Comment by turnerth** [comment] 2018-09-06 17:55
Hi. We pushed out a new script version.  Please give it a try!

**Closed by turnerth** 2018-09-06 17:55 UTC
